source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-active-model-serializers'
gem 'thin'
gem 'rake'

gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'

gem 'history_scraper'
gem 'json'

group :development do
  gem 'annotate'
  gem 'shotgun'
  gem 'hirb'
end
