development:
  adapter : postgresql
  pool    : 5
  host    : localhost
  port    : 5432
  database: OTDAPI_development

production:
  adapter : postgresql
  pool    : 5
  host    : postgres_db
  port    : 5432
  database: OTDAPI_production
  username: postgres
